export enum MutationType {
  INFLOW = 'INFLOW',
  OUTFLOW = 'OUTFLOW',
}

export enum MutationReason {
  SUPPLIER_RESTOCK = 'SUPPLIER_RESTOCK',
  CUSTOMER_SALE = 'CUSTOMER_SALE',
  STOLEN = 'STOLEN',
  DAMAGED = 'DAMAGED',
  EXPIRED = 'EXPIRED',
  AUDIT_CORRECTION = 'AUDIT_CORRECTION',
  NEW_PRODUCT_INITIALIZATION = 'NEW_PRODUCT_INITIALIZATION',
}
